[project]
name = "fastapi-cloud-cli"
dynamic = []
description = "Deploy and manage FastAPI Cloud apps from the command line 🚀"
authors = [
    { name = "Patrick Arminio", email = "patrick@fastapilabs.com" },
]
requires-python = ">=3.10"
readme = "README.md"
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "typer >= 0.16.0",
    "uvicorn[standard] >= 0.17.6",
    "rignore >= 0.5.1",
    "httpx >= 0.27.0",
    "rich-toolkit>=0.20.1",
    "pydantic[email] >= 2.7.4; python_version < '3.13'",
    "pydantic[email] >= 2.8.0; python_version == '3.13'",
    "pydantic[email] >= 2.12.0; python_version >= '3.14'",
    "sentry-sdk >= 2.20.0",
    "fastar >= 0.10.0",
    "detect-installer>=0.1.0",
]
version = "0.22.0"

[project.license]
text = "MIT"

[project.optional-dependencies]
standard = [
    "uvicorn[standard] >= 0.15.0",
]

[project.urls]
Homepage = "https://github.com/fastapilabs/fastapi-cloud-cli"
Documentation = "https://fastapi.tiangolo.com/fastapi-cloud-cli/"
Repository = "https://github.com/fastapilabs/fastapi-cloud-cli"
Issues = "https://github.com/fastapilabs/fastapi-cloud-cli/issues"
Changelog = "https://github.com/fastapilabs/fastapi-cloud-cli/blob/main/release-notes.md"

[dependency-groups]
dev = [
    "prek>=0.2.24,<1.0.0",
    "pytest>=7.0.0,<10.0.0",
    "coverage[toml]>=7.2,<8.0",
    "mypy==2.1.0",
    "ruff>=0.15.16",
    "respx==0.23.1",
    "time-machine>=2.19.0",
    "ty>=0.0.25",
    "zizmor>=1.24.1",
]
github-actions = [
    "smokeshow>=0.5.0",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "src/fastapi_cloud_cli/__init__.py"

[tool.pdm.build]
source-includes = [
    "tests/",
    "scripts/",
]

[tool.pytest.ini_options]
addopts = [
    "--strict-config",
    "--strict-markers",
]
xfail_strict = true
junit_family = "xunit2"

[tool.coverage.run]
parallel = true
data_file = "coverage/.coverage"
source = [
    "src",
    "tests",
]
relative_files = true
context = "${CONTEXT}"
dynamic_context = "test_function"
omit = [
    "tests/assets/*",
]

[tool.coverage.report]
show_missing = true
sort = "-Cover"
exclude_lines = [
    "pragma: no cover",
    "@overload",
    "if __name__ == \"__main__\":",
    "if TYPE_CHECKING:",
]

[tool.coverage.html]
show_contexts = true

[tool.mypy]
strict = true
exclude = [
    "tests/assets/*",
]

[tool.ty.src]
exclude = [
    "tests/assets/**",
]

[tool.ty.terminal]
error-on-warning = true

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
    "B008",
    "C901",
    "W191",
]

[tool.ruff.lint.isort]
known-third-party = [
    "typer",
    "fastapi",
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.typos.files]
extend-exclude = [
    "uv.lock",
    "coverage/",
    "htmlcov/",
]

[tool.typos.default]
extend-ignore-re = [
    "@[a-zA-Z0-9](?:-?[a-zA-Z0-9])*",
]

[tool.typos.default.extend-identifiers]
alls = "alls"
