[build-system]
requires = ['flit_core >=3.11,<4']
build-backend = 'flit_core.buildapi'

[tool.flit.sdist]
include = [
    'docs/',
    'tests/',
    'bin/',
    '*.rst',
    'tox.ini',
]
exclude = [
    'docs/_build/',
]

[project]
name = 'blessed'
description = """\
    Easy, practical library for making terminal apps, by providing an elegant, \
    well-documented interface for Terminals.\
"""
authors = [
    {name = 'Jeff Quast, Erik Rose, Avram Lubkin', email = 'contact@jeffquast.com'},
]

classifiers = [
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Environment :: Console :: Curses',
    'Operating System :: POSIX',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: User Interfaces',
    'Topic :: Terminals',
    'Typing :: Typed',
]
dependencies = [
    'wcwidth>=0.8.1',
    'jinxed>=2.1,<3',
]
dynamic = ['version']
license = 'MIT'
license-files = ['LICENSE']
keywords = ['terminal', 'sequences', 'tty', 'curses', 'ncurses', 'formatting',
            'style', 'color', 'console', 'keyboard', 'ansi', 'xterm']
readme = 'docs/intro.rst'
requires-python = '>=3.8'

[project.optional-dependencies]
docs = [
    'Pillow',
    'Sphinx>3',
    'sphinx-paramlinks',
    'sphinx_rtd_theme',
    'sphinxcontrib-manpage',
]

[project.urls]
Homepage = 'https://github.com/jquast/blessed'
Documentation = 'https://blessed.readthedocs.io'
Repository = 'https://github.com/jquast/blessed'
Issues = 'https://github.com/jquast/blessed/issues'
Changelog = 'https://blessed.readthedocs.io/en/latest/history.html'

[tool.pylint.main]
load-plugins = [
    'pylint.extensions.check_elif',
    'pylint.extensions.docparams',
    'pylint.extensions.dunder',
    'pylint.extensions.for_any_all',
    'pylint.extensions.mccabe',
    'pylint.extensions.overlapping_exceptions',
    'pylint.extensions.redefined_loop_name',
    'pylint.extensions.redefined_variable_type',
    'pylint.extensions.set_membership',
    'pylint.extensions.consider_ternary_expression',
]
persistent = false
jobs = 0

[tool.pylint.'messages control']
enable = ['all']
disable= [
    'fixme',
    'locally-disabled',
    'suppressed-message',
    'wrong-import-order',
    'wrong-import-position',
    'too-few-public-methods',
    'use-implicit-booleaness-not-comparison-to-zero',
]

[tool.pylint.format]
max-line-length = 100
good-names = ['ks', 'fd', '_', 'x' ,'y']

[tool.pylint.parameter_documentation]
default-docstring-type= 'sphinx'
accept-no-raise-doc = false
accept-no-param-doc = true
accept-no-return-doc = true

[tool.pylint.design]
max-args = 10
max-attributes = 7
max-branches = 12
max-complexity = 11
max-locals = 15
max-module-lines = 2000
max-parents = 7
max-public-methods = 20
max-returns = 7
max-statements = 50

[tool.pylint.similarities]
ignore-imports = true
min-similarity-lines = 8

[tool.pylint.reports]
reports = false
msg-template = '{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'
