[build-system]
requires = ["setuptools", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "ai4rag"
description = "Automatic and optimized RAG Pattern generator"
authors = [{ name = "IBM"}]
maintainers = [
    { name = "Jakub Walaszczyk", email = "jwalaszc@redhat.com" },
    { name = "Lukasz Cmielowski", email = "lcmielow@redhat.com" },
    { name = "Michal Steczko", email = "msteczko@redhat.com" },
    { name = "Filip Komarzyniec", email = "fkomarzy@redhat.com"}
]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.12,<3.14"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
]
keywords = [
    "AI",
    "RAG",
    "LLM",
    "GenAI"
]
dynamic = ["version"]

dependencies = [
    "langchain~=1.1.3",
    "langchain_chroma~=1.1.0",
    "langchain-text-splitters~=1.1.0",
    "ogx-client~=1.0.0",
    "pandas==2.2.*",
    "pydantic==2.11.*",
    "pygam~=0.12.0",
    "scikit-learn==1.8.*",
    "unitxt~=1.26.1",
]


[project.urls]
Homepage = "https://github.com/IBM/ai4rag"
Repository = "https://github.com/IBM/ai4rag"
Issues = "https://github.com/IBM/ai4rag/issues"
Documentation = "https://ibm.github.io/ai4rag/"


[project.optional-dependencies]
dev = [
    "ai4rag[test]",
    "ai4rag[code_check]",
    "ai4rag[docs]",
    "beautifulsoup4",      # reading data from html
    "dotenv",
    "ipykernel",
    "docling",             # document text extraction
]

test = ["pytest", "pytest-cov", "pytest-mock", "psutil", "nbformat"]

code_check = ["pylint", "black", "isort"]

docs = [
    "mkdocs~=1.6.0",
    "mkdocs-material~=9.5",
    "mkdocstrings[python]>=0.25.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mike>=2.0.0",
]

[tool.setuptools.dynamic]
version = { attr = "ai4rag.__version__" }

[tool.setuptools.packages.find]
exclude = ["tests*", "dev_utils*"]
namespaces = false


[tool.pytest.ini_options]
python_files = ["tests/**/*.py"]
log_cli = false
log_level = "INFO"

[tool.coverage.run]
# Skipping function templates for notebooks
omit = [
    "ai4rag/core/experiment/experiment.py",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
py_version = 313
line_length = 120
skip = ["scripts/"]


[tool.pylint]
disable = ["missing-module-docstring", "too-few-public-methods", "arguments-differ"]
max-line-length = 120
max-args = 8
max-positional-arguments = 8
max-attributes = 10
