[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80", "setuptools-scm>=8"]

[dependency-groups]
dev = [
  {include-group = "docs-build"},
  {include-group = "qa"},
  {include-group = "type-check"},
  {include-group = "unit-tests"}
]
docs-build = [
  "myst-parser>=4.0.1",
  "pydata-sphinx-theme>=0.19.0",
  "sphinx>=8.1.3",
  "sphinx-autoapi>=3.8.0"
]
integration-tests = [
  {include-group = "unit-tests"},
  "ecmwf-datastores-client[legacy]"
]
qa = [
  "pre-commit>=4.6.0",
  "ruff>=0.15.19"
]
type-check = [
  "mypy>=2.1.0",
  "types-requests>=2.33.0.20260518"
]
unit-tests = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-httpbin>=2.1.0",
  "responses>=0.26.2",
  "urllib3>=2.7.0"
]

[project]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering"
]
dependencies = [
  "attrs>=23.1.0",
  "multiurl>=0.3.7",
  "requests>=2.5.0",
  "typing-extensions>=4.13.0"
]
description = "ECMWF Data Stores Service (DSS) API Python client"
dynamic = ["version"]
license = "Apache-2.0"
license-files = ["LICENSE"]
name = "ecmwf-datastores-client"
readme = "README.md"
requires-python = ">= 3.10"

[project.optional-dependencies]
legacy = [
  "cdsapi >= 0.7.6"
]

[tool.coverage.run]
branch = true

[tool.git-clone]
repo-list = []

[tool.mypy]
explicit_package_bases = true
strict = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "cdsapi.*",
  "multiurl.*",
  "pytest_httpbin.*"
]

[tool.pytest.ini_options]
markers = [
  "extra: additional tests skipped by CI"
]
python_files = [
  "test_*.py"
]
testpaths = [
  "tests"
]

[tool.ruff]
# Same as Black.
indent-width = 4
line-length = 88
target-version = "py310"

[tool.ruff.lint]
ignore = [
  # pydocstyle: Missing Docstrings
  "D1"
]
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I",
  # pydocstyle
  "D",
  # flake8-future-annotations
  "FA",
  # pyupgrade
  "UP"
]

[tool.ruff.lint.pycodestyle]
max-line-length = 110

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.setuptools]
packages = ["ecmwf.datastores"]

[tool.setuptools.package-data]
"ecmwf.datastores" = ["py.typed"]

[tool.setuptools_scm]
fallback_version = "999"
version_scheme = "semver-pep440"
write_to = "ecmwf/datastores/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''

[tool.uv]
exclude-newer = "1 week"

[tool.uv.sources]
ecmwf-datastores-client = {workspace = true}
