[project]
name = "sqlite-migrate"
version = "0.2"
description = "Compatibility package for sqlite-utils migrations"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Simon Willison"}]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 7 - Inactive"
]

dependencies = [
    "sqlite-utils>=4"
]

[project.urls]
Homepage = "https://github.com/simonw/sqlite-migrate"
Changelog = "https://github.com/simonw/sqlite-migrate/releases"
Issues = "https://github.com/simonw/sqlite-migrate/issues"
CI = "https://github.com/simonw/sqlite-migrate/actions"

[dependency-groups]
dev = ["pytest", "mypy", "black", "cogapp"]

[build-system]
requires = ["uv_build>=0.9.18,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
