[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fla-core"
version = "0.5.2"
description = "Core operations for flash-linear-attention"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = ["einops"]

[project.urls]
Homepage = "https://github.com/fla-org/flash-linear-attention"
Repository = "https://github.com/fla-org/flash-linear-attention"

[project.optional-dependencies]
cuda = ["torch>=2.7.0", "triton>=3.3"]
rocm = ["torch>=2.7.0"]
xpu = ["torch>=2.7.0"]
npu = ["torch==2.7.1", "torch_npu==2.7.1.post4", "torchvision==0.22.1", "triton-ascend==3.2.1"]
cpu = ["torch>=2.7.0", "triton>=3.3"]


[tool.setuptools.packages.find]
include = ["fla*"]
namespaces = true
